version: '3.3'
services:
  elective:
    image: postgres:13
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mobile
    networks:
      - kushagra
networks:
  kushagra:
